### ISSUE TITLE
Callbackurl

### ISSUE THREAD

**Issue by 16isaac89** [creativeJoe007/react-native-rave-webview#3]
Hi creativeJoe007
Thanks for the package, how do i set the callback url to a backend url(Am using php/laravel as my back end)
thank you

**Comment by creativeJoe007** [comment]
You can tie your backend endpoint to the onSuccess handler.

That's if you want to perform an action after payment has been made.

**Comment by 16isaac89** [comment]
i did that but it shows a white screen after payment is successful  or on cancelling the process,

**Comment by creativeJoe007** [comment]
This issue has been resolved in the new update
